version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - APP_ENV=development
      # For local development with Docker Postgres
      - DATABASE_URL=postgres://postgres:postgres@db:5432/inventory?sslmode=disable
      - DATABASE_NO_SSL_URL=postgres://postgres:postgres@db:5432/inventory?sslmode=disable
      # Uncomment and update these for Supabase (production)
      # - DATABASE_URL=postgres://postgres:[YOUR-PASSWORD]@db.awqcdpsyqfdazxonieyt.supabase.co:5432/postgres?sslmode=verify-full&host=db.awqcdpsyqfdazxonieyt.supabase.co
      # - DATABASE_NO_SSL_URL=postgres://postgres:[YOUR-PASSWORD]@db.awqcdpsyqfdazxonieyt.supabase.co:5432/postgres?sslmode=prefer&host=db.awqcdpsyqfdazxonieyt.supabase.co
    depends_on:
      - db

  # Local development database
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Test database
  db-test:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_test
    ports:
      - '5433:5432'
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  postgres-test-data:
